actor_lr: 3e-4
actor_dropout: 0.1
batch_size: 256
beta: 3.0
buffer_size: 10000000
checkpoints_path: null
device: cuda
discount: 0.99
env: door-cloned-v1
eval_freq: 5000
group: IQL-D4RL
iql_deterministic: false
iql_tau: 0.8
load_model: ''
offline_iterations: 1000000
online_iterations: 1000000
n_episodes: 10
name: IQL_door-cloned-v1
normalize: true
normalize_reward: false
qf_lr: 3e-4
project: CORL
seed: 0
tau: 0.005
vf_lr: 3e-4
