actor_lr: 3e-4
batch_size: 256
beta: 10.0
buffer_size: 10000000
checkpoints_path: null
device: cuda
discount: 0.99
env: antmaze-umaze-v2
eval_freq: 50000
group: IQL-D4RL
iql_deterministic: false
iql_tau: 0.9
load_model: ''
offline_iterations: 1000000
online_iterations: 1000000
n_episodes: 100
name: IQL_antmaze-umaze-v2
normalize: true
normalize_reward: true
qf_lr: 3e-4
project: CORL
seed: 0
tau: 0.005
vf_lr: 3e-4
